stages:
- test
- build

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

build-job:
  stage: build
  image: nimlang/nim
  script:
    - apt-get -y install build-essential
    - make build_deb
  artifacts:
    paths:
      - "bin/"
