stages:
- test
- build

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

build-job:
  stage: build
  image: nimlang/nim
  script:
    - nimble install --opt:size --passL:-static
    - strip bin/battinfo
  artifacts:
    paths:
      - "bin/"
