stages:
- test
- build

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

build-job:
  stage: build
  image: nimlang/nim
  script:
    - nim c -d:release -o:bin/battinfo --opt:size --passL:-static src/battinfo.nim
    - strip bin/battinfo
  artifacts:
    paths:
      - "bin/"
